const SchoolData = [
    
    "Kean University", "Montclair State University","New Jersey City University",
    "New Jersey Institute of Technology","Ramapo College","Rowan University",
    "Rutgers University","Stockton University","The College of New Jersey",
    "William Paterson University","Bloomfield College","Caldwell University",
    "Drew University","Fairleigh Dickinson University","Monmouth University",
    "Princeton University","Rider University","Seton Hall University",
    "Stevens Institute of Technology","Atlantic Cape Community College","Bergen Community College",
    "Brookdale Community College","Camden County College","County College of Morris",
    "Essex County College","Hudson County Community College","Mercer County Community College",
    "Middlesex County College","Ocean County College","Passaic County Community College",
    "Raritan Valley Community College","Rowan College at Burlington County","Rowan College of South Jersey",
    "Salem Community College","Sussex County Community College","Union County College",
    "Warren County Community College",
    

"Binghamton University",
"Stony Brook University",
"University at Albany",
"University at Buffalo",
"Buffalo State College",
"Empire State College",
"Purchase College",
"State University of New York at Geneseo",
"State University of New York at New Paltz",
"State University of New York at Oswego",
"State University of New York at Potsdam",
"SUNY Cortland",
"SUNY College at Oneonta",
"SUNY Fredonia",
"SUNY Plattsburgh",
"The College at Brockport",
"The College at Old Westbury",
"Alfred State College",
"Farmingdale State College",
"Fashion Institute of Technology",
"Morrisville State College",
"SUNY Canton",
"SUNY Cobleskill",
"SUNY Delhi",
"SUNY Maritime College",
"SUNY Adirondack",
"SUNY Broome",
"Cayuga Community College",
"Clinton Community College",
"Columbia-Greene Community College",
"Corning Community College",
"Dutchess Community College",
"SUNY Erie",
"Fashion Institute of Technology",
"Finger Lakes Community College",
"Fulton-Montgomery Community College",

"Genesee Community College",
"Herkimer County Community College",
"Hudson Valley Community College",
"Jamestown Community College",
"Jefferson Community College",
"Mohawk Valley Community College",
"Monroe Community College",
"Nassau Community College",
"Niagara County Community College",
"North Country Community College",
"Onondaga Community College",
"Orange County Community College",
"Rockland Community College",
"SUNY Schenectady",
"Suffolk County Community College",
"Sullivan County Community College",
"Tompkins Cortland Community College",
"Ulster County Community College",
"Westchester Community College",
"Baruch College",
"City College of NY",
"CUNY Graduate Center",
"Graduate School of Journalism",
"Hunter College",
"John Jay College of Criminal Justice",
"Macaulay Honors College",
"Borough of Manhattan Community College",
"School of Professional Studies",
"School of Public Health",
"CUNY School of Medicine",
"Bronx Community College",
"Hostos Community College",
"Lehman College",
"Brooklyn College",
"NYC College of Technology",
"Kingsborough Community College",
"Medgar Evers College",
"College of Staten Island",
"LaGuardia Community College",
"Queens College",
"Queensborough Community College",
"School of Law",
"York College",
"Guttman Community College",

"Albert Einstein College of Medicine",
"American Academy of Dramatic Arts",
"American Academy McAllister Institute",
"American Musical and Dramatic Academy",
"ASA College",
"Bank Street College of Education",
"Bard College Graduate Center",
"Barnard College",
"Berkeley College",
"Boricua College",
"Brooklyn Law School",
"Christie's Education",
"College of Mount Saint Vincent",
"Columbia University",
"Cooper Union",
"Cornell University",
"DeVry University",
"Fordham University",
"Frank G. Zarb School of Business at Hofstra University[1]",
"General Theological Seminary",
"Gerstner Sloan Kettering Graduate School of Biomedical Science",
"Globe Institute of Technology",
"Hebrew Union College",
"Helene Fuld College of Nursing",
"Icahn School of Medicine at Mount Sinai",
"Jewish Theological Seminary of America",
"The Juilliard School",
"The King's College",
"Laboratory Institute of Merchandising",
"Long Island Business Institute - Flushing",
"Long Island University",
"Mandl College of Allied Health",
"Manhattan College",
"Manhattan School of Music",
"Marymount Manhattan College",
"Mercy College",
"Metropolitan College of New York",
"Monroe College",
"The New School",
"New York Academy of Art",
"New York Conservatory for Dramatic Arts",
"New York Film Academy",
"New York Graduate School of Psychoanalysis",
"New York Institute of Technology",
"New York Law School",
"New York School of Interior Design",
"New York Theological Seminary",
"New York University",
"Nyack College",
"Pace University",
"Pacific College of Oriental Medicine",
"Phillips Beth Israel School of Nursing",
"Plaza College",

"Pratt Institute",
"Rabbi Isaac Elchanon Theological Seminary",
"Richard Gilder Graduate School",
"Rockefeller University",
"School of American Ballet",
"School of Visual Arts",
"St. Francis College",
"St. John's University",
"St. Joseph's College",
"Sotheby's Institute of Art",
"Swedish Institute of Massage Therapy",
"Touro College",
"Vaughn College of Aeronautics & Technology",
"Wagner College",
"Yeshiva University",
    
    ]
export default SchoolData